---
title: "Datasets explenations details"
output: html_document
---

# Accessible Data in the Shiny App

This Shiny application provides access to several datasets that allow for a thorough exploration of data from the Global Tuna Atlas database. Each dataset comes with a detailed explanation and a DOI identifier, which can be found in the table below. These details aim to provide you with precise context and technical insights into the accessible data.

The following dataset can be found under the following DOI. For each dataset a abstract is provided for more comprehensive choosing. Please contact us if you need more information.


<!-- ```{r include=FALSE} -->

<!-- require(flextable) -->
<!-- require(readr) -->

<!-- metadata_dcmi <- as.data.frame(read_csv(here::here("DOI.csv"))) -->

<!-- ``` -->


<!-- ```{r echo=FALSE, results='asis'} -->

<!-- knitr::kable(metadata_dcmi, format = "markdown", caption = "Details of Accessible Datasets") -->


<!-- ``` -->

| DOI                     | Filename                                |
|--------------------------|-----------------------------------------|
| 10.5281/zenodo.14184244 | global_catch_tunaatlasird_level2 (without_geom).csv |
| 10.5281/zenodo.11460074 | global_catch_firms_level0_harmonized.csv |



## Recommendations for data selection

Currently, we strongly advise opting for `global_catch_tunaatlasird_level2` data. This recommendation is based on the accessibility and the richness of information these data provide, making exploration and analysis both simpler and more rewarding.

## Display of grid types

It is crucial to note that our application does not support the display of multiple grid types simultaneously. To maximize the value of the explored information, we recommend using datasets that are already aggregated into 5-degree grids. This approach prevents the selection of a specific grid type, which could lead to a partial loss of available information.

By choosing aggregated data, you benefit from a comprehensive and consolidated view, thus facilitating the identification of trends and patterns within the data.





