main_panel_ui = function()
  {
  nav_panel(
title = "GTA Shiny App",
card(
  full_screen = TRUE,
  card_header(
    "Indicators for Fisheries: use case of the Tuna Atlas
        "
  ),
  card_body(
    "Key elements of the analysis code are a set of indicators originally drafted by Alain Fontenau which were written in R by Norbert Billet and Julien Barde during iMarine FP7 project:
        
        Shiny apps have been set up to help newcomers to explore easily the data by using the set of indicators generated by analysis code. Users of shiny apps interested in the code will rather use the related jupyternotebooks than shinyp apps source code.
        
        These Shiny apps have been developped and executed in the Fisheries Atlas VRE which contains a RStudio server for developpers and a shiny proxy server to host these apps.",
    grid_container(
      layout = c(
        "howtouse updates",
        "Fundings Authors"
      ),
      row_sizes = c(
        "1fr",
        "1fr"
      ),
      col_sizes = c(
        "1fr",
        "1fr"
      ),
      gap_size = "10px",
      grid_card(
        area = "updates",
        full_screen = TRUE,
        card_header("Updates of data"),
        card_body(
          "The input data are expected to be updated on a yearly basis by FAO and IRD. This update is managed by a set of dedicated scripts:
              
              IRD legacy SQL code: the persistent storage of data is ensured by a PostgreSQL / Postgis database / multi-dimensionnal data warehouse -- first version has been set up by Jean Jacques Lechauve in early 2000's -- a second version has been set up in 2015 by Paul Taconet, Emmanuel Chassot, Julien Barde
              IRD legacy R code: the current R code is mainly coming from -- a translation in R of previous Fortran code (Alain and Viveca Fonteneau) achived by Julien Trollet -- the packaging of previous R code within a workflow: Paul Taconet, Emmanuel Chassot, Julien Barde. See Paul Taconet github repositories rtunaatlas and rtunaatlas_scripts
              IRD and FAO/FIRMS Tuna Atlas update to manage previous IRD workflow with geoflow and related package to manage OGC standards (provided by Emmanuel Blondel): see geoflow-tunaatlas \n"
        )
      ),
      grid_card(
        area = "Fundings",
        full_screen = TRUE,
        card_header("Fundings"),
        card_body(
          paste0("This work received funding from:
              
              IRD
              iMarine FP7 project
              BlueBridge H2020 project:BlueBRIDGE receives funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No. 675680
              Blue Cloud H2020 project: Blue-Cloud has received funding from the European Union's Horizon programme call BG-07-2019-2020, topic: [A] 2019 - Blue Cloud services, Grant Agreement n.862409. The views and opinions expressed in this website are the sole responsibility of the author and do not necessarily reflect the views of the European Commission."
        ), 
        create_logo_panel())
      ),
      grid_card(
        area = "Authors",
        full_screen = TRUE,
        card_header("Authors"),
        card_body(
          "Multiple contributors have been helping building this repository: Julien Barde, Norbert Billet, Emmanuel Chassot, Taha Imzilen, Paul Taconet, Bastien Grasset, UMR MARBEC..."
        )
      ),
      grid_card(
        area = "howtouse",
        full_screen = TRUE,
        card_header("How to use this shiny app ?"),
        card_body(
          "This shiny app allows to explore different data of the Global Tuna Atlas. For each indicators you want to explore, choose your dataset and your filters then click to submit.
          Caution, sometimes the map can take a bit of time before plotting the object.
               "
        )
      )
    )
  )
)
)
}
