main_panel_ui = function()
  {
  nav_panel(
    title = "GTA Shiny App",
    card(
      full_screen = TRUE,
      card_header(
        "Indicators for Fisheries: use case of the Tuna Atlas"
      ),
      card_body("test",
        "This shiny app allows to explore different data of the Global Tuna Atlas. For each indicators you want to explore, choose your dataset and your filters then click to submit.
                          Caution, sometimes the map can take a bit of time before plotting the object.

                        Shiny apps have been set up to help newcomers to explore easily the data by using the set of indicators generated by analysis code. Users of shiny apps interested in the code will rather use the related jupyternotebooks than shinyp apps source code.

                        These Shiny apps have been developped and executed in the Fisheries Atlas VRE which contains a RStudio server for developpers and a shiny proxy server to host these apps.
                The data displayed is from several datasets having for each specificities. \n
                Global_catch firms level 0 \n
                Global catch firms level 1 \n
                Global catch firms level 2 \n

                For each dataset a doi and more exaplanation can be found on",
        grid_container(
          layout = c(
            "howtouse datadisplayed",
            "Fundings Authors"
          ),
          row_sizes = c(
            "1.73fr",
            "0.27fr"
          ),
          col_sizes = c(
            "900px",
            "1fr"
          ),
          gap_size = "10px",
          grid_card(
            area = "datadisplayed",
            full_screen = TRUE,
            card_header("Data displayed"),
            card_body(
              grid_container(
                layout = c(
                  "map_example  example_plot",
                  "example_grid example_query"
                ),
                row_sizes = c(
                  "0.91fr",
                  "1.09fr"
                ),
                col_sizes = c(
                  "0.99fr",
                  "1.01fr"
                ),
                gap_size = "10px",
                grid_card(
                  area = "map_example",
                  card_body('plotOutput(outputId = "plot")')
                ),
                grid_card(
                  area = "example_plot",
                  card_body('plotOutput(outputId = "plot")')
                ),
                grid_card(
                  area = "example_grid",
                  card_body('DTOutput(outputId = "myTable", width = "100%")')
                ),
                grid_card_text(
                  content = "Text for card",
                  alignment = "center",
                  area = "example_query"
                )
              )
            )
          ),
          grid_card(
            area = "Fundings",
            full_screen = TRUE,
            card_header("Fundings"),
            card_body(
              paste0("This work received funding from:

                                          IRD
                                          iMarine FP7 project
                                          BlueBridge H2020 project:BlueBRIDGE receives funding from the European Union’s Horizon 2020 research and innovation programme under grant agreement No. 675680
                                          Blue Cloud H2020 project: Blue-Cloud has received funding from the European Union's Horizon programme call BG-07-2019-2020, topic: [A] 2019 - Blue Cloud services, Grant Agreement n.862409. The views and opinions expressed in this website are the sole responsibility of the author and do not necessarily reflect the views of the European Commission."
              ),
              create_logo_panel()
            )
          ),
          grid_card(
            area = "Authors",
            full_screen = TRUE,
            card_header("Authors"),
            card_body(
              "Multiple contributors have been helping building this repository: Julien Barde, Norbert Billet, Emmanuel Chassot, Taha Imzilen, Paul Taconet, Bastien Grasset, UMR MARBEC...
                            Key elements of the analysis code are a set of indicators originally drafted by Alain Fontenau which were written in R by Norbert Billet and Julien Barde during iMarine FP7 project:"
            )
          ),
          grid_card(
            area = "howtouse",
            full_screen = TRUE,
            card_header("How to use this shiny app ?"),
            card_body(
              grid_container(
                layout = c(
                  "instruction instruction",
                  "indicator1  button     "
                ),
                row_sizes = c(
                  "1fr",
                  "1fr"
                ),
                col_sizes = c(
                  "1fr",
                  "1fr"
                ),
                gap_size = "10px",
                grid_card_text(
                  content = "Text for card",
                  alignment = "start",
                  area = "instruction"
                ),
                grid_card(
                  area = "indicator1",
                  card_body(
                    card(
                      full_screen = TRUE,
                      card_header(
                        "Example of indicators for Skipjack Tuna in 2000"
                      ),
                      card_body(
                        actionButton(inputId = "buttoni3", label = "i3"),
                        actionButton(inputId = "buttoni2", label = "i2")
                      )
                    )
                  )
                ),
                grid_card(
                  area = "button",
                  card_body(
                    "Example of indicators for Albacore in Indian ocean",
                    actionButton(inputId = "buttoni7", label = "i7"),
                    actionButton(inputId = "buttoni8", label = "i8")
                  )
                )
              )
            )
          )
        )
      )
    )
  )
}

