name: Build and Push DEV Docker Image (with RStudio)

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Branch to base the dev Docker image on"
        required: true
        default: "main"
      push_image:
        description: "Push image to GHCR (true/false)"
        required: true
        default: "false"

env:
  IMAGE_NAME: ghcr.io/firms-gta/tunaatlas_pie_map_shiny-dev
  RENV_PATHS_ROOT: /root/.cache/R/renv
  DOCKER_BUILDKIT: 1

jobs:
  build-dev-image:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout ${{ github.event.inputs.base_branch }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.base_branch }}

      - name: Calculate renv.lock hash
        id: renv_lock
        run: |
          echo "renv_lock_hash=$(sha256sum renv.lock | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Calculate DOI.csv hash
        id: doi_csv
        run: |
          echo "doi_csv_hash=$(sha256sum DOI.csv | cut -d' ' -f1)" >> $GITHUB_ENV

      - name: Log in to GHCR
        if: ${{ github.event.inputs.push_image == 'true' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build dev image
        run: |
          docker buildx build \
            --progress=plain \
            --build-arg MODE=dev \
            --build-arg BASE_IMAGE=rocker/rstudio:4.2.3 \
            --build-arg RENV_LOCK_HASH=${{ env.renv_lock_hash }} \
            --build-arg DOI_CSV_HASH=${{ env.doi_csv_hash }} \
            --tag ${{ env.IMAGE_NAME }}:${{ github.event.inputs.base_branch }} \
            --output type=oci,dest=/tmp/dev-image.tar \
            .

      - name: Load image to Docker
        run: docker load -i /tmp/dev-image.tar

      - name: Push dev image
        if: ${{ github.event.inputs.push_image == 'true' }}
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.event.inputs.base_branch }}
          docker tag ${{ env.IMAGE_NAME }}:${{ github.event.inputs.base_branch }} ${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.IMAGE_NAME }}:latest
