name: Build Slim Docker Image

on:
  workflow_dispatch:
    inputs:
      push_slim:
        description: 'Pousser l’image slim sur GHCR ?'
        required: true
        default: 'false'
        type: boolean

env:
  IMAGE: ghcr.io/firms-gta/tunaatlas_pie_map_shiny:latest

jobs:
  build-slim:
    runs-on: ubuntu-latest

    steps:
    - name: Récupérer le code
      uses: actions/checkout@v3

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Pull base image
      run: |
        docker pull $IMAGE_BASE

    - name: Build & push “light” image on-demand
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.multistage
        push: ${{ inputs.push_light }}
        tags: |
          ${{ env.IMAGE }}
        cache-from: |
          type=registry,ref=${{ env.IMAGE }}
        cache-to: |
          type=inline

    - name: Verify slim image size
      if: always()
      run: |
        echo "Slim image size:"
        docker images $IMAGE_SLIM --format "{{.Repository}}:{{.Tag}}\t{{.Size}}"
