name: Build Slim Docker Image

on:
  workflow_dispatch:
    inputs:
      push_slim:
        description: 'Pousser l’image slim sur GHCR ?'
        required: true
        default: false
        type: boolean

env:
  IMAGE: ghcr.io/firms-gta/tunaatlas_pie_map_shiny

jobs:
  build-slim:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull base & cache
      run: |
        docker pull $IMAGE:latest      || true
        docker pull $IMAGE:latest-cache || true

    - name: Original image size
      run: |
        echo "::group::Taille de l'image de base"
        docker images $IMAGE:latest \
          --format "{{.Repository}}:{{.Tag}}\t{{.Size}}"
        echo "::endgroup::"

    - name: Build & push slim image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile.multistage
        push: ${{ inputs.push_slim }}
        tags: |
          ${{ env.IMAGE }}:latest
        cache-from: |
          type=registry,ref=${{ env.IMAGE }}:latest-cache
        cache-to: |
          type=registry,ref=${{ env.IMAGE }}:latest-cache,mode=max
    
    - name: Docker disk usage
      run: docker system df

    - name: Verify slim image size (remote)
      run: |
        echo "::group::Taille de l'image slim sur GHCR"
        docker manifest inspect $IMAGE:latest | \
          grep size | \
          awk '{total += $2} END {print total/1024/1024 " MB"}'
        echo "::endgroup::"

