name: Mirror to Forge IRD
on:
  push:
    branches: ["**"]
    tags: ["**"]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Push --mirror to GitLab (marbec/globaltunaatlas)
        run: |
          git remote add mirror https://oauth2:${{ secrets.TOKEN_MIRROR_GITHUB_ON_GITLAB }}@forge.ird.fr/marbec/globaltunaatlas/tunaatlas_pie_map_shiny.git
          git push --mirror mirror
